on:
  pull_request:
    branches: main

name: Quarto PR Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update ubuntu packages
        run: sudo apt-get update

      - name: Install ubuntu dependencies
        run: sudo apt-get install -y --no-install-recommends libpango1.0-dev

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto
        run: uv run quarto render .
